fix: remove unused dataset transform for CzechProductReviewSentimentClassification
was not removed in: https://github.com/embeddings-benchmark/mteb/pull/4172

leads to this error:
```
ValueError: Original column names {'rating_str', 'comment'} not in the dataset. Current columns in the dataset: ['text', 'label']