model: fix revision for jinav5
Previously had this error (likely as we were missing [this](https://huggingface.co/jinaai/jina-embeddings-v5-text-small/commit/1b04d2c4323d58f9068152575445be97d7551b92))

cc @michael-guenther

```   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shadeform/.cache/huggingface/modules/transformers_modules/jinaai/jina_hyphen_embeddings_hyphen_v5_hyphen_text_hyphen_small/46ed7da5b47e4bca710b756313fafaf4110c6bd1/custom_st.py", line 32, in __init__
    self.config = AutoConfig.from_pretrained(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: transformers.models.auto.configuration_auto.AutoConfig.from_pretrained() got multiple values for keyword argument 'cache_dir'