model: Add missing required dependencies to jina models (#4564)
get the following when running
````
ImportError: This modeling file requires the following packages that were not found in your environment: peft. Run `pip install peft`